Repository pluginkollektiv/statify, pull requests merged in 2020-04, with the labels that each got.

#132 update Chartist JS library for dashboard widget
  CHANGELOG.md
  composer.json
  composer.lock
Labels: enhancement

#72 Introduce option to separately configure storage and display ranges
  CHANGELOG.md
  inc/class-statify-dashboard.php
  inc/class-statify-settings.php
  inc/class-statify.php
  views/widget-back.php
Labels: enhancement

#117 Fix target and referer reporting when PHP and database differ on timezone
  CHANGELOG.md
  inc/class-statify-cron.php
  inc/class-statify-dashboard.php
Labels: bug

#101 scrollable chart
  CHANGELOG.md
  css/dashboard.css
  js/dashboard.js
Labels: enhancement

#116 Issue #110 "JS tracking and AMP compatibility"
  CHANGELOG.md
  inc/class-statify-frontend.php
  inc/class-statify-settings.php
  inc/class-statify.php
Labels: enhancement

#143 widget UI corrections + meta links below settings
  css/dashboard.css
  inc/class-statify-settings.php
  views/widget-back.php
Labels: ui/ux
