Repository pluginkollektiv/statify, pull requests merged in 2023-03, with the labels that each got.

#239 update Chartist library to v1.3
  composer.json
  js/dashboard.js
  package-lock.json
  package.json
Labels: enhancement, dependencies

#247 Replaced bot detection with JayBizzle/Crawler-Detect
  composer.json
  inc/class-statify-frontend.php
  phpcs.xml
  readme.txt
  statify.php
Labels: enhancement, Cloudfest

#252 Replace some deprecated hooks with their new recommended ones
  inc/class-statify.php
Labels: Cloudfest

#248 Adds option to settings page to show stats for different roles
  inc/class-statify-dashboard.php
  inc/class-statify-settings.php
  inc/class-statify.php
  tests/test-dashboard.php
  tests/test-statify.php
Labels: enhancement, Cloudfest, Feature CF, GUI CF

#250 Adds sorting for target / referrer to the data for the dashboard widget
  inc/class-statify-dashboard.php
  tests/test-dashboard.php
Labels: bug, Cloudfest

#255 Improve the field explanation for "Disallowed Comment Keys" (#245)
  inc/class-statify-settings.php
Labels: enhancement, ui/ux
